# Generated by Django 3.1.dev20200103093658 on 2020-05-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_content',
        ),
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='Set a poll name', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
