# Generated by Django 3.1.dev20200103093658 on 2020-06-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200531_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='PUBLISH'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.CharField(max_length=200, verbose_name='Election'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='Set an election name', max_length=200, verbose_name='Election name'),
        ),
    ]
